a1 = input('location on earth')
a2= input("time period")
a3 = input("onomatopoeia (ending in ing)")
a4 = input ("a verb (ending in ed)")
a5 = input( "adverb")
a6 = input("amount of time passing ( like minutes,hours,days)")
a7 = input(' past tense action word')
a8 = input(' another amount of time')
a9 = input('adverb')
a10 = input('adverb')
print("James and I took a nice stroll through " + a1 + " around " + a2 + ". While we were walking through the woods it began to rain and thunder " + a3 + "and we were very " + a4 + ". We decided to hurry up and run to get out, while running we found a cabin and " + a5 + " ran inside it and wait the storm out. A couple of " + a6 + " went by before the lighting from the storm " + a7 + " the cabin and set it on fire, we began panicking for " + a8 + " sacred for our life's. We " + a9 + " got out of there and " + a10 + " out of there and went home.")
 